src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 *  @Vich\Uploadable
 *  @UniqueEntity("titre")
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;


    /**
     * @ORM\Column(type="boolean", options={"default": true})
     */
    private $disponible = true;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $etat;


    /**
     * @ORM\Column(type="integer", length=120)
     */
    private $price;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * 
     * @Assert\Image(mimeTypes={"image/jpeg", "image/jpg", "image/png"})
     * 
     * @Vich\UploadableField(mapping="produit_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->titre);
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }



    /**
     * Get the value of disponible
     */
    public function getDisponible()
    {
        return $this->disponible;
    }

    /**
     * Set the value of disponible
     *
     * @return  self
     */
    public function setDisponible($disponible)
    {
        $this->disponible = $disponible;

        return $this;
    }



    /**
     * Get the value of filename
     *
     * @return  string|null
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set the value of filename
     *
     * @param  string|null  $filename
     *
     * @return  self
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }


    /**
     * Get mimeTypes="image/jpeg"
     *
     * @return  File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     *
     * @param File|null $imageFile
     *
     * @return self
     */
    public function setImageFile(?File $imageFile = null)
    {
        $this->imageFile = $imageFile;

        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }

        return $this;
    }

    /**
     * Get the value of reference
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * Set the value of reference
     *
     * @return  self
     */
    public function setReference($reference)
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * Get the value of etat
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * Set the value of etat
     *
     * @return  self
     */
    public function setEtat($etat)
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * Get the value of price
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set the value of price
     *
     * @return  self
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Intl\Countries;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface,\Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $commandes;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $stripeId;


    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

   

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles() {
        $roles = $this->roles;

        if (empty($roles)) {
            $roles[] = 'ROLE_USER';
        }
        return array_unique($roles);
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt() {
        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials() {

    }

    public function serialize () {
        return serialize([
            $this->id,
            $this->username,
            $this->password,
            $this->mail
        ]);
    }
    public function unserialize ($serialized) {
        
        list(
            $this->id,
            $this->username,
            $this->password,
            $this->mail
        ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getStripeId(): ?string
    {
        return $this->stripeId;
    }

    public function setStripeId(?string $stripeId): self
    {
        $this->stripeId = $stripeId;

        return $this;
    }

    /**
     * Get the value of country
     */ 
    public function getCountries()
    {
        return Countries::getNames();
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\AdresseUser;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Common\Persistence\ObjectManager;
use App\Repository\ProduitRepository;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Commande;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;

class PanierController extends AbstractController
{


    /**
     * @var ProduitRepository
     */
    private $produitRepository;


    /**
     * @var SessionInterface
     */
    private $session;


    /**
     * @var ObjectManager
     */
    private $em;

    /**
     * @var CommandeRepository
     */
    private $repositoryCommande;

    public function __construct(ProduitRepository $produitRepository, SessionInterface $session, EntityManagerInterface $em, CommandeRepository $repositoryCommande)
    {

        $this->produitRepository = $produitRepository;
        $this->session = $session;
        $this->em = $em;
        $this->repositoryCommande = $repositoryCommande;
    }


    /**
     * Supprime le produit dans la session
     * @Route("/produit/supprimer/{id}", name="produit_supprimer")
     * @return Response
     */
    public function supprimeProduitAction(int $id)
    {

        $panier = $this->session->get('panier');
        if (array_key_exists($id, $panier)) {
            unset($panier[$id]);
            $this->session->set('panier', $panier);
            $this->addFlash('danger', 'Votre article a bien été supprimé');
        }
        return $this->redirectToRoute('produit_panier');
    }

    /**
     * Rajoute des produits dans la session
     * @Route("/produit/ajouter/{id}", name="produit_ajouter")
     * @return Response
     */
    public function ajouteProduitAction(int $id, Request $request)
    {

        // on verifie si ca existe la cle(variable) panier dans la session
        // si non on defini cette cle
        // on recupere la cle et on fait des verifications indiqués en dessous
        // ensuite on verifie si le produit existe deja dans la session en verifiant son id 
        // si oui alors on modifie juste sa quantité | on affecte a ce produit la quantité
        // sinon non on rajoute la quantité

        if (!$this->session->has('panier')) {
            $this->session->set('panier', []);
        };

        $panier = $this->session->get('panier');

        if (array_key_exists($id, $panier)) {
            // on passe directement par listing des produits
            if ($request->get('qte') !== null) {
                // on affecte | on modifie la quantité
                $panier[$id] = $request->get('qte');
                $this->addFlash('success', 'Quantité modifié avec succès');
            }
        } else {
            // sinon on ajoute la quantité
            if ($request->get('qte') !== null) {
                $panier[$id] = $request->get('qte');
            } else {
                $panier[$id] = 1;
                $this->addFlash('success', 'Votre article a bien été ajouté');
            }
        }


        $this->session->set('panier', $panier);
        //dd($panier);
        return $this->redirectToRoute('produit_panier');
    }

    /**
     * Affiche la page des produits 
     * @Route("/panier", name="produit_panier")
     * @return Response
     */
    public function panierAction(Request $request)
    {

        if (!$this->session->has('panier')) {
            $this->session->set('panier', []);
        }

        $panier = $this->session->get('panier');

        // on recupere les cles des produits en question dans la panier
        // on va chercher dans la table des produits les id correspondant a ces produits
        $produits = $this->produitRepository->findArray(array_keys($panier));
        return $this->render('panier/panier.html.twig', [
            'produits' => $produits,
            'articles' => count($panier),
            'panier' => $panier,
            'current_menu' => 'panier'
        ]);

        $this->render('panier/panier.html.twig');
    }

    /**
     * on appelle a notre objet commandeController 
     * ici on envoie l'entite commande a la vue
     * et on recupere les infos depuis le tableux de commande
     * 
     * @Route("/validation", name="validation")
     * @return Response
     */
    public function validationAction(CommandeController $prepareCommande, Request $request)
    {
        if (!$this->session->has('adresse')) {
            $this->session->set('adresse', []);
        }
        $adresse = $this->session->get('adresse');

        if (!$request->get('livraison') !== null && null !== $request->get('facturation')) {
            $adresse['livraison']  = $request->get('livraison');
            $adresse['facturation']  = $request->get('facturation');
        }

        $this->session->set('adresse', $adresse);

        $prepareCommandeAction = $prepareCommande->prepareCommandeAction();
        $commande = $this->repositoryCommande->find($prepareCommandeAction->getContent());
        $adresseLivraison = $this->getDoctrine()->getRepository(AdresseUser::class)->findOneBy(
            ['user' => $this->getUser()]
        );
        return $this->render('panier/validation.html.twig', [
            'commande' => $commande,
            'articles' => count($this->session->get('panier')),
            'adresseLivraison' => $adresseLivraison
        ]);
    }
}

templates/panier/livraison.html.twig
{% extends "base.html.twig" %}

{% block title 'Livraison' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="">
            <h2>Livraison</h2>
            <div id="collapseOne" class="accordion-body  in">
                <div class="accordion-inner row">
                    <div class="span4">
                        {% if adresses|length != 0 %}
                        <div class="row">
                        <div class="col-12 col-md-12">
                            <form action="{{path('validation')}}" method="POST">
                                <h4>Adresse de livraison</h4>
                                {% for adresse in adresses %}
                                    <label class="radio">
                                        <input type="radio" name="livraison" id="livraison" value="{{adresse.id}}" {% if loop.index0 == 0%}checked="checked"{% endif %}>
                                        {{adresse.adresse}}, {{adresse.cp}} {{adresse.ville}} - {{adresse.pays}} <a href=""><span class="oi oi-trash"></span></a><br>
                                        {{adresse.prenom}} {{adresse.name}}
                                    </label>
                                {% endfor %}
                                <br>
                                <h4>Adresse de facturation</h4>
                                {% for adress in adresses %}
                                    <label class="radio">
                                        <input type="radio" name="facturation" id="facturation" value="{{adress.id}}" {% if loop.index0 == 0%}checked="checked"{% endif %}>
                                        {{adress.adresse}}, {{adress.cp}} {{adress.ville}} - {{adress.pays}}<a href=""><span class="oi oi-trash"></span></a><br>
                                        {{adress.prenom}} {{adress.name}}
                                    </label>
                                {% endfor %}
                                <button class="btn btn-primary">Valider mon adresse de livraison</button>
                            </form>
                        </div>
                        </div>
                        {% endif %}   
                    </div>

                    <div class="span8">
                        <h4>Ajouter une nouvelle adresse</h4>
                        {{ form_start(form) }}
                        {{ form_rest(form)}}
                            <button class="btn btn-primary">Ajouter</button>
                        {{ form_end(form) }}
                   
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/panier/panier.html.twig
{% extends "base.html.twig" %}

{% block title %}Panier
{% endblock %}

{% set totalHT = 0 %}
{% set totalTVA = 0 %}

{% block body %}

	<div class="container">

		<div class="row">

			<div class="col-3">
				{% include "_panier.html.twig" %}
				{% if app.user %}
					{% include "_factures.html.twig" %}
				{% endif %}
			</div>

			<div class="col-9">
				{% for message in app.flashes('danger') %}
					<div class="alert alert-danger">
						{{ message }}
					</div>
				{% endfor %}
				{% for message in app.flashes('success') %}
					<div class="alert alert-success">
						{{ message }}
					</div>
				{% endfor %}
				<h2>Votre parnier</h2>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>Références</th>
							<th>Quantité</th>
							<th>Prix unitaire</th>
							<th>Total HT</th>
						</tr>
					</thead>
					<tbody>
						{% if produits|length == 0 %}
							<tr>
								<td colspan="4">Aucun article dans votre panier</td>
							</tr>
						{% endif %}

						{% for produit in produits %}
							<tr>
								<form action="{{path('produit_ajouter', {id: produit.id})}}" method="get">
									<td>{{ produit.titre }}</td>
									<td>
										<img style="width:40px; height: 40px" class="block_container_image" src="{{vich_uploader_asset(produit, 'imageFile')}}">
									</td>
									<td>
										<select name="qte" class="span1" onchange="this.form.submit()">
											{% for i in 1..10 %}
												<option value="{{ i }}" {% if i == panier[produit.id] %} selected="selected" {% endif %}>{{ i }}</option>
											{% endfor %}
										</select>&nbsp;
										<a href="{{path('produit_supprimer', {id: produit.id})}}">
											<i class="fas fa-trash-alt"></i>
										</a>
									</td>
									<td>{{produit.formattedPrice}}€</td>
									<td>{{produit.price * panier[produit.id]}}€</td>
								</tr>
							</tr>
						</form>
					</tbody>
				</tr>
				{% set totalHT = totalHT + (produit.price * panier[produit.id]) %}
				{% set totalTVA = totalTVA + (produit.price * panier[produit.id])%}
			{% endfor %}
		</tbody>
	</table>
	{% if produits|length != 0 %}
		<dl class="dl-horizontal pull-right">
			<dt>Total HT :</dt>
			<dd>{{totalHT}}€</dd>
			{# {% if vat %}	
							<dt>Total TTC (TVA {{ vat | price_format('%') }})</dt>
							<dd>{{(produit.price * (vat + 100) / 100)}}€</dd>
						{% endif %} #}
		</dl>
		{% if app.user %}
			<a href="{{path('validation')}}" class="btn btn-success pull-right">Valider mon panier</a>
		{% else %}
			<a href="{{path('login')}}" class="btn btn-success pull-right">Passer Commande</a>
		{% endif %}
		<a href="{{ path('produit_index')}}" class="btn btn-primary">Continuer mes achats</a>
	{% endif %}
</div></div></div>{% endblock %}

templates/panier/validation.html.twig
{% extends "base.html.twig" %}

{% block stylesheets %}
  <style>
    .MyCardElement {
      height: 40px;
      padding: 10px 12px;
      width: 100%;
      color: #32325d;
      background-color: white;
      border: 1px solid transparent;
      border-radius: 4px;
      box-shadow: 0 1px 3px 0 #e6ebf1;
      -webkit-transition: box-shadow 150ms ease;
      transition: box-shadow 150ms ease;
    }
    .MyCardElement--focus {
      box-shadow: 0 1px 3px 0 #cfd7df;
    }
    .MyCardElement--invalid {
      border-color: #fa755a;
    }
    .MyCardElement--webkit-autofill {
      background-color: #fefde5 !important;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2>
          Acheter
          {% if articles == 1 %}
            votre produit
          {% elseif articles > 1 %}
            vos produits
          {% endif %}
        </h2>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Références</th>
              <th>Quantité</th>
              <th>Prix unitaire</th>
              <th>Total HT</th>
            </tr>
          </thead>
          <tbody>
            {% for produit in commande.commande.produit %}
              <tr>
                <td>{{ produit.reference }}</td>
                <td>
                  {{ produit.quantite }}
                </td>
                <td>{{ produit.prixHT }}
                  €</td>
                <td>{{ produit.prixHT * produit.quantite }}
                  €</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <dl class="dl-horizontal pull-right">
          <dt>Total HT :</dt>
          <dd>{{ commande.commande.prixHT }}€</dd>
         
          <dt>Total TTC :</dt>
          <dd>{{ commande.commande.prixTTC }}€</dd>
        </dl>

        {% if adresseLivraison is not defined %}
          <a href="{{path('livraison')}}" class="btn btn-success pull-right">Valider mon panier</a>
        {% endif %}
        {% if adresseLivraison %}  
         <div class="span3 pull-left">
            <dl class="pull-left">
                <dt><h4>Adresse de livraison</h4></dt>
                <dt>{{ commande.commande.livraison.prenom }} {{ commande.commande.livraison.name }}</dt>
                <dt>{{ commande.commande.livraison.adresse }}</dt>
                <dt>{{ commande.commande.livraison.cp }} {{ commande.commande.livraison.ville }} - {{ commande.commande.livraison.pays }}</dt>
            </dl>
          </div>
        
          <div class="span3 pull-left">
            <dl class="pull-left">
                <dt><h4>Adresse de facturation</h4></dt>
                <dt>{{ commande.commande.facturation.prenom }} {{ commande.commande.facturation.name }}</dt>
                <dt>{{ commande.commande.facturation.adresse }}</dt>
                <dt>{{ commande.commande.facturation.cp }} {{ commande.commande.facturation.ville }} - {{ commande.commande.facturation.pays }}</dt>
            </dl>
          </div>
          <div class="clearfix">       
            <h2>Informations de la carte</h2>
            <form action={{path('validationCommande', {id: commande.id})}} id="subscription-form" method="POST">
              <div id="card-element" class="MyCardElement">
                <!-- Elements will create input elements here -->
              </div>

              <!-- We'll put the error messages in this element -->
              <div id="card-errors" role="alert"></div>

              <h3 style="margin-top:20px;">Adresse de facturation</h3>

              <input placeholder="Ville" name="city" type="text" class="input_city form-control verified"/>
              <select name="country" class="input_country form-control verified" placeholder="Pays"> 
                <option value="0">Selectionnez votre pays</option>
                {% for key, country in app.user.countries %}
                  <option value={{key}}>{{ country}}</option>
                {% endfor %}
              </select>
              <input placeholder="Address ligne 1" name="address1" type="text" class="input_address1 form-control verified"/>
              <input placeholder="Address ligne 2" name="address" type="text" class="input_address2 form-control verified"/>
              <input type="hidden" name="stripeToken" class="stripeToken"></input>
              <button class="submit" type="submit">Payer</button>
            </form>
            <a href="{{ path('produit_panier') }}" class="btn btn-primary pull-left">retour</a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

{% if adresseLivraison %}
  
  {% block javascripts %}
    <script src="https://js.stripe.com/v3/"></script>
    <script>
      window.addEventListener('load', function () {
        console.log('I\'m loading Stripe !!!!')
        let stripe = Stripe('pk_test_DuXAPj9VX2bRENW50llmkpuO006SHcVC1R');
        var elements = stripe.elements()
        var style = {
          base: {
            color: '#32325d',
            fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
            fontSmoothing: 'antialiased',
            fontSize: '16px',
            '::placeholder': {
              color: '#aab7c4'
            }
          },
          invalid: {
            color: '#fa755a',
            iconColor: '#fa755a'
          }
        }
        var cardElement = elements.create('card', {style: style})
        cardElement.mount('#card-element')
        const form = document.getElementById('subscription-form')
        const formInput = Array.from(document.querySelectorAll('.verified'))

        form.addEventListener('submit', async (event) => {
          // We don't want to let default form submission happen here,
          // which would refresh the page.
          event.preventDefault()

          let city = form.querySelector('.input_city')
          let country = form.querySelector('.input_country')
          let address1 = form.querySelector('.input_address1')
          let address2 = form.querySelector('.input_address2')

          await stripe.createToken(cardElement, {
            "address_city": city.value,
            "address_country": country.value,
            "address_line1": address1.value,
            "address_line2": address2.value,
          }).then(result => {
            if (result.token) {
              form.querySelector('.stripeToken').setAttribute('value', result.token.id)
              form.querySelector('.submit').setAttribute('disabled', 'disabled')
              form.querySelector('.submit').innerText = 'Chargement...'
              form.submit()
            } else {
              document.querySelector('#card-errors').innerText = result.error.message
              console.log(result.error)
            }
          })
        })
      })
    </script>
  {% endblock %}
{% endif %}